version: "3.8"
services:
  backend-next:
    image: node:18
    container_name: anythink-backend-node
    command: sh -c "yarn && yarn dev"

    working_dir: /usr/src
    volumes:
      - .:/usr/src/
    ports:
      - "3000:3000"
